openapi: 3.0.1
info:
    title: Recipe shopping list
    description: Get shopping list of items for a requested recipe
    version: "v1"
servers:
    - url: [YOUR_DOMAIN, must be HTTPS]
paths:
    /stock:
        get:
            operationId: getIngredientData
            summary: Retrieves the product name and link to product page for each required item
            parameters:
                - in: query
                  name: symbol
                  schema:
                      type: string
                  description: The symbol of the stock to get a quote for. For example, the stock symbol MSFT represents the company Microsoft.
            responses:
                "200":
                    description: OK